apiVersion: v1
kind: ConfigMap
metadata:
  name: clue-server-conf
{{- $Global := . }}
data:
  config.yml: |-
    {{- tpl (toYaml .Values.config) $ | nindent 4 }}

  classification.yml: |-
    {{- tpl (toYaml .Values.classification) $ | nindent 4 }}
