apiVersion: v1
kind: ConfigMap
metadata:
  name: clue-plugin-conf
{{- $Global := . }}
data:
  config.yml: |-
    {{- omit .Values.config "api" "auth" | toYaml | nindent 4 }}

  classification.yml: |-
    {{- toYaml .Values.classification | nindent 4 }}
