apiVersion: v1
kind: Service
metadata:
  name: clue-rest
  labels:
    app: clue-rest
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.port | default 5000 }}
    targetPort: 5000
    protocol: TCP
    name: rest
  selector:
    app.kubernetes.io/name: {{ include "clue.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: rest
