apiVersion: v1
kind: Service
metadata:
  name: clue-web
  labels:
    app: clue-web
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.ui.port | default 3000 }}
    targetPort: 3000
    protocol: TCP
    name: web
  selector:
    app.kubernetes.io/name: {{ include "clue.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: ui
