apiVersion: v1
entries:
  clue-plugin:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2025-11-27T13:56:13.01289953-05:00"
    description: A Helm chart for Kubernetes
    digest: 288f384fb6abb3f752a7afa05c8817e148639c2dfd6abf8bdb526965ef4a6e90
    name: clue-plugin
    type: application
    urls:
    - clue-plugin-0.1.0.tgz
    version: 0.1.0
generated: "2025-11-27T13:56:13.012023027-05:00"
