name: Clue crt.sh Plugin

on:
  push:
    branches:
      - main
      - develop
      - rc/*
      - patch/*
    paths:
      - plugins/crtsh/**
      - .github/workflows/crtsh-plugin-workflow.yml
      - .github/workflows/*-plugin.yml
    tags:
      - v*
  pull_request:
    branches:
      - main
      - develop
      - rc/*
      - patch/*
    paths:
      - plugins/crtsh/**
      - .github/workflows/crtsh-plugin-workflow.yml
      - .github/workflows/*-plugin.yml
  workflow_dispatch: {}
  workflow_run:
    workflows:
      - Clue Base Plugin Image
    types:
      - completed

permissions:
  contents: read
  pull-requests: write

jobs:
  check-crtsh-plugin-formatting:
    name: Lint crt.sh Plugin
    uses: ./.github/workflows/lint-plugin.yml
    with:
      plugin-path: plugins/crtsh
  build-crtsh-plugin:
    needs: check-crtsh-plugin-formatting
    name: Build crt.sh Plugin's Docker Image
    uses: ./.github/workflows/build-plugin.yml
    with:
      plugin-path: plugins/crtsh
    permissions:
      id-token: write
      contents: read
      attestations: write
    secrets: inherit
