name: Clue Malware Bazaar Plugin

on:
  push:
    branches:
      - main
      - develop
      - rc/*
      - patch/*
    paths:
      - plugins/malware_bazaar/**
      - .github/workflows/malware-bazaar-plugin-workflow.yml
      - .github/workflows/*-plugin.yml
    tags:
      - v*
  pull_request:
    branches:
      - main
      - develop
      - rc/*
      - patch/*
    paths:
      - plugins/malware_bazaar/**
      - .github/workflows/malware-bazaar-plugin-workflow.yml
      - .github/workflows/*-plugin.yml
  workflow_dispatch: {}
  workflow_run:
    workflows:
      - Clue Base Plugin Image
    types:
      - completed

permissions:
  contents: read
  pull-requests: write

jobs:
  check-malware-bazaar-plugin-formatting:
    name: Lint Malware Bazaar Plugin
    uses: ./.github/workflows/lint-plugin.yml
    with:
      plugin-path: plugins/malware_bazaar
  test-malware-bazaar-plugin:
    needs: check-malware-bazaar-plugin-formatting
    name: Test Malware Bazaar Plugin
    uses: ./.github/workflows/test-plugin.yml
    with:
      plugin-path: plugins/malware_bazaar
  build-malware-bazaar-plugin:
    needs: test-malware-bazaar-plugin
    name: Build Malware Bazaar Plugin's Docker Image
    uses: ./.github/workflows/build-plugin.yml
    with:
      plugin-path: plugins/malware_bazaar
    permissions:
      id-token: write
      contents: read
      attestations: write
    secrets: inherit
